# Get help her https://aka.ms/yaml

name: cd-$(Date:yyyy-MM-dd)-v$(Rev:r)

trigger: none

stages:
  - stage: release

    variables:
      - name: pathToProject
        value: 'src/SolidifyProject.Engine.CLI/SolidifyProject.Engine.CLI.csproj'

    jobs:
      - job: linux
        strategy:
          matrix:
            linux:
              buildPlatform: linux-x64
            windows:
              buildPlatform: win-x64
            macos:
              buildPlatform: osx-x64

        pool:
          vmImage: 'ubuntu-16.04'
        workspace:
          clean: outputs
        steps:

          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(pathToProject)'
              arguments: '-r $(buildPlatform) --self-contained -c Release -o $(Build.ArtifactStagingDirectory)/$(buildPlatform)/engine'
              zipAfterPublish: false
              modifyOutputPath: false

          