name: cd-$(Date:yyyy-MM-dd)-v$(Rev:r)

trigger: none

stages:
  - stage: release

    variables:
      - name: pathToProject
        value: 'src/SolidifyProject.Engine.CLI/SolidifyProject.Engine.CLI.csproj'

    jobs:
      - job: publish
        strategy:
          matrix:
            linux:
              buildPlatform: linux-x64
            windows:
              buildPlatform: win-x64
            macos:
              buildPlatform: osx-x64

        pool:
          vmImage: 'ubuntu-20.04'
        workspace:
          clean: outputs
        steps:

          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK 2.1'
            inputs:
              packageType: 'sdk'
              version: '2.1.x'

          - task: DotNetCoreCLI@2
            displayName: 'Restore, Build and Publish CLI'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(pathToProject)'
              arguments: '-r $(buildPlatform) --self-contained -c Release -o $(Build.ArtifactStagingDirectory)/$(buildPlatform)/engine'
              zipAfterPublish: false
              modifyOutputPath: false

          - task: CopyFiles@2
            displayName: 'Copy shared artifacts'
            inputs:
              SourceFolder: '_publish/all'
              Contents: '**/*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/$(buildPlatform)'

          - task: CopyFiles@2
            displayName: 'Copy platform specific artifacts'
            inputs:
              SourceFolder: '_publish/$(buildPlatform)'
              Contents: '**/*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/$(buildPlatform)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(buildPlatform)'
              ArtifactName: '$(buildPlatform)'
              publishLocation: 'Container'
