trigger: none

pool:
  # Windows Server 2019 with Visual Studio 2019
  vmImage: 'windows-2019'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.x'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'solidify-project'
    scannerMode: 'MSBuild'
    projectKey: 'solidify-project-engine'
    projectName: 'Solidify Project Engine'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src\SolidifyProject.Engine.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: 'src\SolidifyProject.Engine.sln'
    vsVersion: '16.0'
    clean: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src\Test\SolidifyProject.Engine.Test.Unit\**\*test*.dll'
    arguments: '-l trx'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'