# Get help her https://aka.ms/yaml

name: ci-$(Date:yyyy-MM-dd)-v$(Rev:r)

trigger:
  - master

pr:
  - master

stages:
  - stage: build_test

    variables:
      - name: pathToSolution
        value: 'src/SolidifyProject.Engine.sln'
      - name: pathToUnitTests
        value: 'src/Test/SolidifyProject.Engine.Test.Unit/SolidifyProject.Engine.Test.Unit.csproj'
      - name: pathToIntegrationTests
        value: 'src/Test/SolidifyProject.Engine.Test.Integration/SolidifyProject.Engine.Test.Integration.csproj'

    jobs:
      - job: linux
        pool:
          vmImage: 'ubuntu-18.04'
        workspace:
          clean: outputs
        steps:

          - template: 'template.build.yaml'
            parameters:
              pathToSolution: $(pathToSolution)

          - template: 'template.test.yaml'
            parameters:
              pathToProject: $(pathToUnitTests)
              name: 'Unit tests on Linux'

          - template: 'template.test.yaml'
            parameters:
              pathToProject: $(pathToIntegrationTests)
              name: 'Integration tests on Linux'


      - job: windows
        pool:
          vmImage: 'windows-2019'
        workspace:
          clean: outputs
        steps:

          - template: 'template.build.yaml'
            parameters:
              pathToSolution: $(pathToSolution)

          - template: 'template.test.yaml'
            parameters:
              pathToProject: $(pathToIntegrationTests)
              name: 'Integration tests on Windows'


      - job: macos
        pool:
          vmImage: 'macOS-10.15'
        workspace:
          clean: outputs
        steps:

          - template: 'template.build.yaml'
            parameters:
              pathToSolution: $(pathToSolution)

          - template: 'template.test.yaml'
            parameters:
              pathToProject: $(pathToIntegrationTests)
              name: 'Integration tests on Mac'
